config/routes.rb
Rails.application.routes.draw do

  resources :payments,only: [:create]
  post "payment/create", to: "checkout#create"

  resources :rooms do
    resources :messages
  end  
  
  devise_for :users
  resources :orders

#   resources :cartitems do  
#    resources :orders do
#   end
# end


  root "homes#index"


  resource :cart, only: [:show], as: "user_cart", path: "users/:user_id/cart"

  resources :cart do
    resources :cartitems do
      get :increase_quantity
      get :decrease_quantity
      get :remove_item
    end
  end

  resources :restaurants do
    resources :fooditems
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
  user ||= User.new
  
  
  if user.admin?
    can :manage, Restaurant
    can :manage, Fooditem
    
  else 
    can :read, Restaurant
    can :read, Fooditem
  end 
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cartitems
  validates :user_id, presence: true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :fooditem
  belongs_to :cart
  enum status: [:quantity]
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
   belongs_to :restaurant
   has_many :cartitems
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many  :fooditems, dependent: :destroy
    validates :name, :address, presence: true
    validates :name, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
 validates_uniqueness_of :name
 scope :public_rooms, -> { where(is_private: false) }
 after_create_commit { broadcast_append_to 'rooms' }
 has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_one :cart
  has_many :orders
  after_create :set_cart
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to 'users' }
  
  has_many :messages
  
  private
   
  def set_cart
     Cart.create(user_id: self.id)
  end
 end

app/controllers/fooditems_controller.rb
class FooditemsController < ApplicationController
  before_action :set_restaurant
  before_action :set_fooditem, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    if params[:q].present?
      @fooditems = @restaurant.fooditems.where("name LIKE ?", "%#{params[:q]}%")
    else
      @fooditems = @restaurant.fooditems
    end
    @fooditems = @fooditems.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @fooditem = @restaurant.fooditems.new
  end

  def create
    @fooditem = @restaurant.fooditems.new(fooditem_params)
    if @fooditem.save
      redirect_to restaurant_fooditems_path(@restaurant), notice: 'Fooditem was successfully created.'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @fooditem.update(fooditem_params)
      redirect_to restaurant_fooditems_path(@restaurant), notice: 'Fooditem was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @fooditem.destroy
    redirect_to restaurant_fooditems_path(@restaurant), notice: 'Fooditem was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_fooditem
    @fooditem = @restaurant.fooditems.find(params[:id])
  end

  def fooditem_params
    params.require(:fooditem).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/fooditems/edit.html.erb
<h1> Edit Food Items</h1>
<h3><%= @fooditem.name %></h3>
<%= form_with model:[@restaurant , @fooditem]  do |form| %>
 <div class = "form-group">
   <%= form.label :name%>
   <%= form.text_field :name,class: "form-control" %> 
 </div>
 <div class = "form-group">
   <%= form.label :Description%>
   <%= form.text_field :description,class: "form-control" %> 
 </div>
 <div class = "form-group">
   <%= form.label :price%>
   <%= form.text_field :price,class: "form-control" %> 
 </div>
  <div>
    <%= form.submit "Update Fooditem" %>
  </div>
 <%end%>

app/views/fooditems/index.html.erb
<div class="container">
  <h3>Food Items</h3>
  <%= form_tag(restaurant_fooditems_path(@restaurant), method: :get, class: 'form-inline my-3') do %>
    <%= text_field_tag :q, params[:q], placeholder: "Search...", class: "form-control me-2" %>
    <%= submit_tag "Search", class: "btn btn-outline-primary" %>
  <% end %>

  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @fooditems.each do |fooditem| %>
        <tr>
          <td><%= fooditem.name %></td>
          <td><%= fooditem.description %></td>
          <td><%= fooditem.price %></td>
          <td>
            <% if current_user.admin? %>
              <%= link_to "Create Fooditem", new_restaurant_fooditem_path(@restaurant), class: "btn btn-outline-primary mr-1" %>
              <%= link_to "Edit", edit_restaurant_fooditem_path(@restaurant, fooditem), class: "btn btn-outline-primary mr-1" %>
              <%= button_to "Delete", restaurant_fooditem_path(@restaurant, fooditem), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-primary mr-1" %>
            <% else %>
              <%= button_to "Add", cart_cartitems_path(current_user.cart, fooditem_id: fooditem.id), method: :post, class: "btn btn-outline-primary mr-1" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @fooditems, class: 'd-flex justify-content-center' %>
</div>

app/views/fooditems/new.html.erb
<h3> New Food Items </h3>
<%= form_with model:[@restaurant , @fooditem] do |form| %>
 
 <div class= "form-group">
   <%= form.label :name %>
   <%= form.text_field :name ,class: "form-control" %>
 </div>

 <div class="form-group">
  <%= form.label :description%>
  <%= form.text_field :description ,class:"form-control" %>
 </div>

 <div class="form-group">
  <%= form.label :price %>
  <%= form.text_field :price ,class: "form-control" %>
 </div>

<%= form.submit "create food Items", class: "btn btn-primary" %>
<% end %>
 

app/views/fooditems/show.html.erb
<h1>Fooditems#show</h1>
<p>Find me in app/views/fooditems/show.html.erb</p>