config/routes.rb
Rails.application.routes.draw do

  resources :payments,only: [:create]
  post "payment/create", to: "checkout#create"

  resources :rooms do
    resources :messages
  end  
  
  devise_for :users
  resources :orders

#   resources :cartitems do  
#    resources :orders do
#   end
# end


  root "homes#index"


  resource :cart, only: [:show], as: "user_cart", path: "users/:user_id/cart"

  resources :cart do
    resources :cartitems do
      get :increase_quantity
      get :decrease_quantity
      get :remove_item
    end
  end

  resources :restaurants do
    resources :fooditems
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
  user ||= User.new
  
  
  if user.admin?
    can :manage, Restaurant
    can :manage, Fooditem
    
  else 
    can :read, Restaurant
    can :read, Fooditem
  end 
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cartitems
  validates :user_id, presence: true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :fooditem
  belongs_to :cart
  enum status: [:quantity]
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
   belongs_to :restaurant
   has_many :cartitems
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many  :fooditems, dependent: :destroy
    validates :name, :address, presence: true
    validates :name, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
 validates_uniqueness_of :name
 scope :public_rooms, -> { where(is_private: false) }
 after_create_commit { broadcast_append_to 'rooms' }
 has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_one :cart
  has_many :orders
  after_create :set_cart
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to 'users' }
  
  has_many :messages
  
  private
   
  def set_cart
     Cart.create(user_id: self.id)
  end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @cart_items = current_user.cart.cartitems
    if @cart_items.exists?
      @restaurant_id = @cart_items.first.fooditem.restaurant_id
    else
      notice = "not fooditems added"
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/carts/new.html.erb
<%= form_with model: [@restaurant, @fooditem , @cart] do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :fooditem_id, value: fooditem.id %>
  <%= f.submit "Add to Cart" %>
<% end %>

app/views/carts/show.html.erb
<div class="container">
  <h1>My order</h1>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>S.no</th>
        <th>Food Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% total_price = 0 %>
      <% @cart_items.each do |cart_item| %>
        <tr>
          <td><%= @cart_items.index(cart_item) + 1 %></td>
          <td><%= cart_item.fooditem.name %></td>
          <td><%= cart_item.fooditem.price %></td>
          <td><%= cart_item.quantity %></td>
          <td>
            <%= button_to "+", cart_cartitem_path(cart_item.cart, cart_item, context: 'add'), method: :patch, class: "btn btn-success" %>
            <% if cart_item.quantity > 1 %>
              <%= button_to "-", cart_cartitem_path(cart_item.cart, cart_item, context: 'delete'), method: :patch, class: "btn btn-success" %>
            <% end %>
            <%= button_to "Remove", cart_cartitem_path(cart_item.cart, cart_item), method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>
        <% total_price += cart_item.fooditem.price * cart_item.quantity %>
      <% end %>
    </tbody>
  </table>

  <p> Total Price: <%= total_price %></p>

  <%= link_to "Placed Order", new_order_path(restaurant_id: @restaurant_id, fooditem_ids: @cart_items.pluck(:fooditem_id)), class: "btn btn-success" %>
</div>