config/routes.rb
Rails.application.routes.draw do

  resources :payments,only: [:create]
  post "payment/create", to: "checkout#create"

  resources :rooms do
    resources :messages
  end  
  
  devise_for :users
  resources :orders

#   resources :cartitems do  
#    resources :orders do
#   end
# end


  root "homes#index"


  resource :cart, only: [:show], as: "user_cart", path: "users/:user_id/cart"

  resources :cart do
    resources :cartitems do
      get :increase_quantity
      get :decrease_quantity
      get :remove_item
    end
  end

  resources :restaurants do
    resources :fooditems
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
  user ||= User.new
  
  
  if user.admin?
    can :manage, Restaurant
    can :manage, Fooditem
    
  else 
    can :read, Restaurant
    can :read, Fooditem
  end 
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cartitems
  validates :user_id, presence: true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :fooditem
  belongs_to :cart
  enum status: [:quantity]
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
   belongs_to :restaurant
   has_many :cartitems
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many  :fooditems, dependent: :destroy
    validates :name, :address, presence: true
    validates :name, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
 validates_uniqueness_of :name
 scope :public_rooms, -> { where(is_private: false) }
 after_create_commit { broadcast_append_to 'rooms' }
 has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_one :cart
  has_many :orders
  after_create :set_cart
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to 'users' }
  
  has_many :messages
  
  private
   
  def set_cart
     Cart.create(user_id: self.id)
  end
 end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/homes/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="btn btn-primary" href="/">Food App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Add Restaurants", new_restaurant_path ,  class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "View Restaurants", restaurants_path ,  class:"nav-link" %>
            </li>
          <%else%>
            <li class="nav-item">
              <%= link_to "View Restaurants", restaurants_path ,  class:"nav-link" %>
            </li>
          <%end%>
          <li class="nav-item">
            <%= link_to "Cart", user_cart_path(current_user)  ,  class:"nav-link" %>
          </li>
          <div class="nav-item">
            <li>
              <%= link_to "my order" , orders_path , class:"nav-link" %>
            </li>
            <li>
              <%= link_to "Start Chat",  rooms_path, class:"btn btn-outline-primary" %> 
            </li>
          </div>
        <%end %>
      </div>
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete , class: "btn btn-outline-primary"%>
      <%else %>
        <div class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path ,class:"btn btn-outline-primary" %>
        </div>
        <div class="nav-item">
          <%= link_to "Sign in", new_user_session_path,class:"btn btn-outline-primary"%>
        </div>
      <%end %>
    </div>
  </ul>
</div>
</nav>

app/views/homes/index.html.erb
<%#= link_to "Open restaurant",restaurants_path, class:"btn btn-primary " , class:"link: center" %>
<%#= render 'homes/footer'%>
<%=image_tag("mainpage", height: '790', width: '1700') %>