config/routes.rb
Rails.application.routes.draw do

  resources :payments,only: [:create]
  post "payment/create", to: "checkout#create"

  resources :rooms do
    resources :messages
  end  
  
  devise_for :users
  resources :orders

#   resources :cartitems do  
#    resources :orders do
#   end
# end


  root "homes#index"


  resource :cart, only: [:show], as: "user_cart", path: "users/:user_id/cart"

  resources :cart do
    resources :cartitems do
      get :increase_quantity
      get :decrease_quantity
      get :remove_item
    end
  end

  resources :restaurants do
    resources :fooditems
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
  user ||= User.new
  
  
  if user.admin?
    can :manage, Restaurant
    can :manage, Fooditem
    
  else 
    can :read, Restaurant
    can :read, Fooditem
  end 
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cartitems
  validates :user_id, presence: true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :fooditem
  belongs_to :cart
  enum status: [:quantity]
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
   belongs_to :restaurant
   has_many :cartitems
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many  :fooditems, dependent: :destroy
    validates :name, :address, presence: true
    validates :name, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
 validates_uniqueness_of :name
 scope :public_rooms, -> { where(is_private: false) }
 after_create_commit { broadcast_append_to 'rooms' }
 has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_one :cart
  has_many :orders
  after_create :set_cart
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to 'users' }
  
  has_many :messages
  
  private
   
  def set_cart
     Cart.create(user_id: self.id)
  end
 end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:destroy, :edit, :show, :update]

  def index
    if params[:q].present?
      @restaurants = Restaurant.where("name LIKE ? OR description LIKE ? OR address LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
                              .paginate(page: params[:page], per_page: 10)
    else
      @restaurants = Restaurant.all.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params_restaurant)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant created successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(params_restaurant)
      redirect_to @restaurant, notice: "Restaurant updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private

  def params_restaurant
    params.require(:restaurant).permit(:name, :description, :address)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= form_with model:@restaurant do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name ,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_field :description, class:"form-control"%>
  </div>
  <div class="form-group">
    <%= form.label :address %><br>
    <%= form.text_field :address,class:"form-group" %>
  </div>
  <div>
    <%= form.submit "Update Restaurant" %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All Restaurants</h1>

  <%= form_tag(restaurants_path, method: :get, class: 'd-flex') do %>
    <%= text_field_tag :q, params[:q], placeholder: "Search...", class: "form-control me-2" %>
    <%= submit_tag "Search", class: "btn btn-outline-primary" %>
  <% end %>

  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Restaurant Name</th>
        <th>Description</th>
        <th>Address</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |rest| %>
        <tr>
          <td><%= rest.name %></td>
          <td><%= rest.description %></td>
          <td><%= rest.address %></td>
          <td class="d-flex">
            <% if current_user.admin? %>
              <%= link_to "View Food Items", restaurant_fooditems_path(rest), class: "btn btn-outline-primary mr-1" %>
              <%= link_to "Update Restaurant", edit_restaurant_path(rest), class: "btn btn-outline-primary mr-1" %>
              <%= button_to "Delete Restaurant", restaurant_path(rest), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary mr-1" %>
            <% else %>
              <%= link_to "Menu", restaurant_fooditems_path(rest), class: "btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <div class="digg_pagination">
      <div class="page_info">
        <%= page_entries_info @restaurants %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
<h1>New Restaurant</h1>
<%= form_with model: @restaurant do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address,class:"form-control" %>
  </div>
  <div>
    <%= form.submit "Create Restaurant" %>
  </div>
<% end %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h1><%= @restaurant.address %></h1>
<h1><%= @restaurant.description %></h1>